### ISSUE TITLE
Design, farger, fonts og templates

### ISSUE THREAD

**Issue by Fridollo** [MariusSjo/fysi#11]
**Is your feature request related to a problem? Please describe.**
Et gjennomgående design gir et godt helhetsinntrykk. Jeg ønsker gjerne at vi skal fortsette å bruke den fargepaletten og fontene fremover også. 

**Describe the solution you'd like**
Fargepalett:
Hvit/Beige: #FFFFF2
Mørkeblå: #1c2848
Eventuelt komplimentere små detaljer med lyseblå: #4d76f0

Font:
PT sans

**Describe alternatives you've considered**
Når det gjelder bakgrunnsfargen på nettsiden er jeg usikker på om f.eks det ville vært kult å ha en mørkeblå bakgrunn. Har også noen design ideer på hvordan bakgrunnen kunne pimpes opp litt. Jeg må bare vite hvor stor størrelse bakgrunnsbildet må ha før jeg designer det i photoshop i så fall. 

**Additional context**
Ønsker gjerne at nettsiden skal ha et "fav icon" (fav-icon er det lille bildet som er i fanen til nettsiden) slik som det er i dag. (Det lille fysi-hodet)

**Comment by Fridollo** [comment]
Det hadde vært kult om bakggrunnen var mørkeblå slik jeg konfigurerte den, men hvis man fikk noen sirkler i lyseblå farge til å flyte litt rundt, så hadde det vært magisk fett.
I liknende stil som dette bildet: 
![Fysi Podcast Cover](https://user-images.githubusercontent.com/123579784/217058039-5fd48426-0189-48f3-a688-25e10fd3394e.png)

**Comment by MariusSjo** [comment]
For lage et nytt issue med boblerequest! Gjerne med screenshot av ønsket design, boblestørrelse, på mobil og desktop.
