### ISSUE TITLE
Podkast episoder i kronologisk rekkefølge

### ISSUE THREAD

**Issue by Fridollo** [MariusSjo/fysi#12]
**Is your feature request related to a problem? Please describe.**
Problemet er at de 3 siste episodene som vises på "hjem" ikke er de 3 nyeste. 
De er heller ikke kronologisk organisert. FYI så la jeg inn alle i kronologisk rekkefølge, fra første episode ever made først til siste publisert til slutt.

**Describe the solution you'd like**
Jeg ønsker at episodene skal være sortert i kronologisk rekkefølge, uten at de viser datoen for når innlegget var laget.

**Describe alternatives you've considered**
Et alternaltiv er at forsiden viser 3 nye "random" episoder fra arkivet for hver gang du besøker nettsiden. Det hadde faktisk vært jævlig kult. 

**Additional context**
Intet mer.

**Comment by MariusSjo** [comment]
Fullt mulig å føre oversikt over episoder man har vært innom også unngå å vise de! På den måten kan man vise de "3 nyeste-ikke sett" episodene!

Dette tror jeg burde beskrives som et eget issue! Da dette er en større task, men skal se om jeg får fikset rekkefølgen snarlig :)
